#!/bin/bash
if [ $power -eq 1 ] > /dev/null 2>&1;
 then
echo " "
echo "As you jettison away from the nightmare of Gargantua-3, you watch as the black hole Captain Tom Skerritt jokingly called /DEV/NULL consumes your former home and everyone inside it. You barely made it out alive, and there is a lot of empty space between you and salvation. Things are grim, but you’ve cheated annihilation before, and you know that you can withstand whatever comes next."
echo " "
cd ../../../
export swallow=1
exec bash
else
echo " "
echo "The escape pod does not have power."
echo " " 
fi
